name: OscarCI (simple / legacy toml file)

on:
   pull_request:
     branches:
       - master

concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  generatematrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      PR_NUMBER: ${{github.event.number}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2.1.0
    - name: "Set up Julia"
      uses: julia-actions/setup-julia@v1
      with:
        version: '~1.6.0-0'
    - id: set-matrix
      # the active_repo here is just to try fetching metadata from some old PR
      # and wont be used for this CI
      run: |
        julia --project=. -e "using Pkg; Pkg.instantiate();
                 using OscarDevTools;
                 ciprefs = OscarDevTools.parse_meta(\"test/meta/OscarCI-legacy.toml\");
                 cimat = OscarDevTools.ci_matrix(ciprefs;
                                   pr=366,
                                   active_repo=\"oscar-system/Singular.jl\");
                 @show cimat;
                 println(OscarDevTools.github_json(cimat));"

  test-oscar:
    needs: generatematrix
    name: ${{ join(matrix.*.name) }} - ${{ matrix.os }}, julia ${{ matrix.julia-version}}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    env:
      PR_NUMBER: ${{github.event.number}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix: ${{fromJSON(needs.generatematrix.outputs.matrix)}}
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.1.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: "Set up Oscar-dev configuration"
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        # we can't use active_repo below as we just have the devtools active
        run: |
          echo "$MATRIX_CONTEXT"
          julia --project=. -e "using Pkg; Pkg.instantiate();
                   using OscarDevTools;
                   pkgs = OscarDevTools.parse_job(ENV[\"MATRIX_CONTEXT\"]);
                   oscar_develop(pkgs;
                                 dir=\"oscar-dev\");"
      - name: "Run Oscar tests"
        run: |
          julia --project=oscar-dev/project/ -e 'using Pkg; Pkg.test("Oscar");'
